#
#
#spring.application.name=Titan_watch_learning_project
#
#server.port=${PORT:8081}
#
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/titan_bot_db}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Sam@12345}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
## Correct Karix Send API URL
#karix.api.url=${KARIX_API_URL:https://rcmapi.instaalerts.zone/services/rcm/sendMessage}
#karix.api.key=${KARIX_API_KEY:eMVmg5PzK2iko9OesbREMQ==}
#karix.waba.number=${KARIX_WABA_NUMBER:916366920144}
#
## Header name: Postman mein jis header se API working hai wahi use karo
## Agar Postman mein Authentication header hai, default same rahega
#karix.auth.header-name=${KARIX_AUTH_HEADER_NAME:Authentication}
#
## Local should process, not forward
#webhook.forward.enabled=${WEBHOOK_FORWARD_ENABLED:false}
#webhook.forward.url=${WEBHOOK_FORWARD_URL:}
#
#titan.catalogue.url=${TITAN_CATALOGUE_URL:https://www.titanwatch.in/birthday-catalogue}
#titan.website.url=${TITAN_WEBSITE_URL:https://www.titanwatch.in}
#titan.banner.image=${TITAN_BANNER_IMAGE:https://picsum.photos/800/400}
#
##cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}
#cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,https://titan-front-end-nu.vercel.app,https://quack-freestyle-slashed.ngrok-free.dev}
#logging.level.com.example.titan_watch_learning_project=DEBUG
#logging.level.org.springframework.web=INFO
#
#
#
#
#jwt.secret=${JWT_SECRET:change-this-secret-to-a-long-secure-key-change-this-secret}
#jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
#
#admin.default.email=${ADMIN_DEFAULT_EMAIL:admin@titan.com}
#admin.default.password=${ADMIN_DEFAULT_PASSWORD:Admin@12345}
#admin.default.name=${ADMIN_DEFAULT_NAME:Titan Admin}
#
#
#
#
#
#
#
##JWT_SECRET=make-this-very-long-random-secret-for-production
##ADMIN_DEFAULT_EMAIL=admin@titan.com
##ADMIN_DEFAULT_PASSWORD=YourStrongPassword@123
##ADMIN_DEFAULT_NAME=Titan Admin






spring.datasource.url=jdbc:mysql://localhost:3306/titan_bot_db
spring.datasource.username=root
spring.datasource.password=Sam@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

karix.api.url=https://rcmapi.instaalerts.zone/services/rcm/sendMessage
karix.api.key=eMVmg5PzK2iko9OesbREMQ==
karix.waba.number=916366920144
karix.auth.header-name=Authentication

webhook.forward.enabled=false
webhook.forward.url=

titan.catalogue.url=https://www.titanwatch.in/birthday-catalogue
titan.website.url=https://www.titanwatch.in
titan.banner.image=https://picsum.photos/800/400

cors.allowed.origins=http://localhost:5173,http://localhost:3000,https://titan-front-end-nu.vercel.app

logging.level.com.example.titan_watch_learning_project=DEBUG
logging.level.org.springframework.web=INFO

jwt.secret=change-this-secret-to-a-long-secure-key-change-this-secret
jwt.expiration-ms=86400000

admin.default.email=admin@titan.com
admin.default.password=Admin@12345
admin.default.name=Titan Admin




#https://quack-freestyle-slashed.ngrok-free.dev/webhook