spring.application.name=Titan_watch_learning_project
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${PORT:8081}


# Dev forward OFF rakho jab local data test karna ho
dev.forward.enabled=true
dev.forward.url=https://sasquatch-hence-ferment.ngrok-free.dev/webhook