spring.application.name=Titan_watch_learning_project

server.port=8081

#azure data base

spring.datasource.url=jdbc:mysql://titan-watch-mysql-prod.mysql.database.azure.com:3306/titan_prod?useSSL=true&requireSSL=true&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=titanadmin
spring.datasource.password=Sam@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000




spring.jackson.time-zone=Asia/Kolkata







server.tomcat.threads.max=500
server.tomcat.threads.min-spare=50
server.tomcat.accept-count=1000
server.tomcat.max-connections=10000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

karix.api.url=https://rcmapi.instaalerts.zone/services/rcm/sendMessage
karix.api.key=eMVmg5PzK2iko9OesbREMQ==
karix.waba.number=916366920144
karix.auth.header-name=Authentication

spring.jms.servicebus.connection-string=Endpoint=sb://titan-watch-servicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=tRhrro02Vq2Q5+93JZ/xZjZj8+GB1wN7Y+ASbLAk7oQ=
spring.jms.servicebus.pricing-tier=basic
spring.jms.listener.auto-startup=true

webhook.forward.enabled=false
webhook.forward.url=

spring.mvc.trailing-slash=false

titan.website.url=https://www.titanwatch.in
cors.allowed.origins=http://localhost:5173,http://localhost:3000,https://titan-front-end-nu.vercel.app,https://tw-dashboard.centralindia.cloudapp.azure.com,https://brave-rock-0a7740c00.7.azurestaticapps.net,http://40.80.81.142

spring.thymeleaf.check-template-location=false

webhook.queue.enabled=true

jwt.secret=change-this-secret-to-a-long-secure-key-change-this-secret
jwt.expiration-ms=86400000

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


logging.file.name=logs/titan-bot.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.level.com.example.titan_watch_learning_project=INFO
logging.level.org.springframework.web=WARN